#pragma once

#include "FileManager.h"
#include "utils.h"

/**
 * @brief Contains routines for generating, storing, and loading simulation datasets.
 * @details This namespace manages the creation of synthetic data for services, devices, 
 * edge servers (EC), cloud servers (CC), and Poisson-based arrival schedules. It ensures 
 * reproducibility by reading from generated files if they already exist, avoiding 
 * redundant calculations across multiple simulation runs.
 */
namespace DataGenerator {
    
    /**
     * @brief Path pointing to the main data directory.
     */
    const std::filesystem::path dataPath = std::filesystem::current_path() / "data";
    
    /**
     * @brief Path pointing to the directory containing base template files.
     */
    const std::filesystem::path basePath = dataPath / "baseFiles";

    /**
     * @brief Generates or loads network service requirement data.
     * @details Creates random service profiles with varying task counts, memory, storage, 
     * and processing demands. Calculates a non-service cost (CND) penalty based on these 
     * hardware requirements. The result is saved to a text file for future runs.
     * 
     * @param numServices The total number of distinct service profiles to generate.
     * @return A 2D string vector containing the generated services dataset.
     */
    inline std::vector<std::vector<std::string>> servicesData(const int numServices = 10) {
        std::filesystem::path servicePath = basePath / "Services.txt";
        if (std::filesystem::exists(servicePath)) {
            return FileManager::read(servicePath.string(), ' ').value_or(std::vector<std::vector<std::string>>{});
        }

        std::vector<std::vector<std::string>> services;
        services.push_back({"#", "CND", "PCC", "PCN", "MEM", "STO", "S_d", "TSK"});

        for (int i = 1; i <= numServices; i++) {
            int tsk = utils::randomNumber(1, 4);
            int pcn = utils::randomNumber(1, 4);
            double s_d = utils::randomNumber(0.00484, 12.0);
            double pcc = 0.0, mem = 0.0, sto = 0.0;
            double cnd = 0.0;

            for (int j = 0; j < tsk; j++) {
                pcc += utils::randomNumber(0.000001, 2.5);
                mem += utils::randomNumber(0.000001, 2.5);
                sto += utils::randomNumber(0.000001, 15.0);
            }
            
            if      (pcn == 1) cnd += 3;
            else if (pcn == 2) cnd += 5;
            else if (pcn == 3) cnd += 7;
            else if (pcn == 4) cnd += 9;
            
            if      (pcc >= 0 && pcc < 2.5)   cnd += 0.3;
            else if (pcc >= 2.5 && pcc < 5)   cnd += 0.5;
            else if (pcc >= 5 && pcc < 7.5)   cnd += 0.7;
            else if (pcc >= 7.5 && pcc <= 10) cnd += 0.9;
            
            services.push_back({
                utils::toString(i), utils::toString(cnd), utils::toString(pcc),
                utils::toString(pcn), utils::toString(mem), utils::toString(sto),
                utils::toString(s_d), utils::toString(tsk)
            });
        }

        if (!FileManager::write(servicePath.string(), services, ' ')) {
            std::cerr << "Error writing to " << servicePath.string() << std::endl;
            return {};
        }
        return services;
    }

    /**
     * @brief Generates or loads device request data representing mobile network users.
     * @details Merges geographic coordinate data from a base device file with random 
     * service requirements generated by `servicesData`. It also calculates a random 
     * Time-To-Live (TTL) representing the active duration of the device.
     * 
     * @param length The total number of devices to generate.
     * @param MAX_TTL The maximum allowable Time-To-Live boundary.
     * @param numServices The number of underlying service templates to sample from.
     * @return A 2D string vector representing the comprehensive devices dataset.
     */
    inline std::vector<std::vector<std::string>> devicesData(const int length, const int MAX_TTL, const int numServices = 10) {
        std::filesystem::path deviceFilePath = dataPath / "devices" / ("Devices_" + std::to_string(length) + ".txt");
        if (std::filesystem::exists(deviceFilePath)) {
            return FileManager::read(deviceFilePath.string(), ' ').value_or(std::vector<std::vector<std::string>>{});
        }

        std::vector<std::vector<std::string>> services = servicesData(numServices);
        if (services.size() <= 1) {
            std::cerr << "Error: No services data available." << std::endl;
            return {};
        }

        std::filesystem::path baseDevicesPath = basePath / "Devices_1000.txt";
        auto devices1000Opt = FileManager::read(baseDevicesPath.string(), ' ');
        if (!devices1000Opt || devices1000Opt->empty()) {
            std::cerr << "Error: Base device data file not found or is empty." << std::endl;
            return {};
        }
        const std::vector<std::vector<std::string>>& devices1000 = *devices1000Opt;

        std::vector<std::vector<std::string>> devices;
        devices.push_back({"#", "LAT", "LON", "CND", "PCC", "PCN", "MEM", "STO", "S_d", "TTL", "File_ID", "TSK", "SVC"});

        
        for (int i = 0; i < length; i++) {
            int randomIdx = utils::randomNumber(0, (int)devices1000.size() - 1);
            const auto& sourceDeviceRow = devices1000.at(randomIdx);
            const auto& sourceServiceRow = services.at(utils::randomNumber(1, (int)services.size() - 1));

            int ttl = 0, MAX_TTL_perTsk = MAX_TTL / 4; //Divide o MAX_TTL pela quantidade de tasks (TSK) para distribuir o TTL proporcionalmente entre as tarefas do serviço.
            for (int j = 0; j < std::stoi(sourceServiceRow.at(7)); j++) {
                ttl += utils::randomNumber(1, MAX_TTL_perTsk);
            }

            devices.push_back({
                utils::toString(i + 1), // Device ID
                sourceDeviceRow.at(1),  // LAT from source device
                sourceDeviceRow.at(2),  // LON from source device
                sourceServiceRow.at(1), // CND from service
                sourceServiceRow.at(2), // PCC from service
                sourceServiceRow.at(3), // PCN from service
                sourceServiceRow.at(4), // MEM from service
                sourceServiceRow.at(5), // STO from service
                sourceServiceRow.at(6), // S_d from service
                utils::toString(ttl),   // TTL from service
                sourceDeviceRow.at(0),  // Device ID from source device
                sourceServiceRow.at(7), // TSK from service
                sourceServiceRow.at(0)  // SVC ID from service
            });
        }

        if (!FileManager::write(deviceFilePath.string(), devices, ' ')) {
            std::cerr << "Error writing to " << deviceFilePath.string() << std::endl;
            return {};
        }
        return devices;
    }

    /**
     * @brief Generates or loads Cloud Computing (CC) server data.
     * @details Reads foundational CC geographic coordinates from a base file and 
     * appends derived processing time capabilities (T_p) based on predefined logic.
     * 
     * @param length The total number of CC servers to generate.
     * @return A 2D string vector containing the CC servers dataset.
     */
    inline std::vector<std::vector<std::string>> ccData(const int length) {
        std::filesystem::path serverFilePath = dataPath / "servers" / ("CC_" + std::to_string(length) + ".txt");
        if (std::filesystem::exists(serverFilePath)) {
            return FileManager::read(serverFilePath.string(), ' ').value_or(std::vector<std::vector<std::string>>{});
        }

        std::filesystem::path sourcePath = basePath / ("CC_" + std::to_string(length) + ".txt");
        auto sourceDataOpt = FileManager::read(sourcePath.string(), ' ');
        if (!sourceDataOpt || sourceDataOpt->empty()) {
            std::cerr << "Error: CC source file not found or is empty: " << sourcePath.string() << std::endl;
            return {};
        }

        std::vector<std::vector<std::string>> cc;
        cc.push_back({"#", "LAT", "LON", "CSC", "PCC", "PCN", "MEM", "STO", "T_p"});
        for (const auto& row : *sourceDataOpt) {
            if (row.at(0) == "#") continue;
            std::vector<std::string> newRow = row;
            newRow.push_back(utils::toString(12.5 / std::stod(row.at(4)))); 
            cc.push_back(newRow);
        }

        if (!FileManager::write(serverFilePath.string(), cc, ' ')) {
            std::cerr << "Error writing to " << serverFilePath.string() << std::endl;
            return {};
        }
        return cc;
    }

    /**
     * @brief Generates or loads Edge Computing (EC) server data.
     * @details Uses geographic base data to anchor Edge Servers, then procedurally 
     * assigns random profiles concerning memory, storage, core count (PCN), processing 
     * capacity (PCC), operational cost (CSC), and processing time (T_p).
     * 
     * @param length The total number of EC servers to generate.
     * @return A 2D string vector containing the EC servers dataset.
     */
    inline std::vector<std::vector<std::string>> ecData(const int length) {
        std::filesystem::path serverFilePath = dataPath / "servers" / ("EC_" + std::to_string(length) + ".txt");
        if (std::filesystem::exists(serverFilePath)) {
            return FileManager::read(serverFilePath.string(), ' ').value_or(std::vector<std::vector<std::string>>{});
        }

        std::filesystem::path sourcePath = basePath / ("EC_" + std::to_string(length) + ".txt");
        auto sourceDataOpt = FileManager::read(sourcePath.string(), ' ');
        if (!sourceDataOpt || sourceDataOpt->empty()) {
            std::cerr << "Error: EC source file not found or is empty: " << sourcePath.string() << std::endl;
            return {};
        }
        const std::vector<std::vector<std::string>>& sourceData = *sourceDataOpt;

        std::vector<std::vector<std::string>> ec;
        ec.push_back({"#", "LAT", "LON", "CSC","PCC", "PCN", "MEM", "STO", "T_p"});

        for (const auto& s : sourceData) {
            if (s.at(0) == "#") continue;
            int raffle = utils::randomNumber(1, 5);
            std::string pcn, pcc, csc;

            if      (raffle == 1) { pcn = "2";  pcc = "1.6"; csc = "0.00085";}
            else if (raffle == 2) { pcn = "4";  pcc = "2.3"; csc = "0.00097";}
            else if (raffle == 3) { pcn = "6";  pcc = "2.9"; csc = "0.00121";}
            else if (raffle == 4) { pcn = "8";  pcc = "3.0"; csc = "0.00138";}
            else                  { pcn = "10"; pcc = "3.0"; csc = "0.00153";}

            double mem = utils::randomNumber(2.5, 125.0);
            double sto = utils::randomNumber(15.0, 1000.0);
            double t_p = 12.5 / std::stod(pcc);

            ec.push_back({
                s.at(0), s.at(1), s.at(2), csc, pcc, pcn,
                utils::toString(mem), utils::toString(sto), utils::toString(t_p)
            });
        }

        if (!FileManager::write(serverFilePath.string(), ec, ' ')) {
            std::cerr << "Error writing to " << serverFilePath.string() << std::endl;
            return {};
        }
        return ec;
    }

    /**
     * @brief Generates or loads a discrete Poisson distribution schedule.
     * @details Provides a time-series vector mapping the volume of incoming devices across steps.
     * It handles two modes mapped via `isDeviceSize`: targeting an exact total number of devices, 
     * or spanning a specific number of time steps.
     * 
     * @param targetOrSize The exact sum of elements (if isDeviceSize=true) or the vector length (if false).
     * @param lambda The mathematical mean arrival parameter for the Poisson formula.
     * @param isDeviceSize Modifies behavior between tracking total devices sum vs tracking fixed time steps.
     * @return A vector of integers, where each element maps to device arrivals at step `i`.
     */
    inline std::vector<int> poissonSchedule(int targetOrSize, int lambda, bool isDeviceSize = true) {
        std::filesystem::path scheduleFilePath;
        if (isDeviceSize) {
            scheduleFilePath = dataPath / "poissonDistribution" / ("Poisson_D" + std::to_string(targetOrSize) + "_L" + std::to_string(lambda) + ".txt");
        } else{
            scheduleFilePath = dataPath / "poissonDistribution" / ("Poisson_" + std::to_string(targetOrSize) + "steps_L" + std::to_string(lambda) + ".txt");
        }
        
        
        std::vector<int> schedule;
        if (std::filesystem::exists(scheduleFilePath)) {
            auto dataOpt = FileManager::read(scheduleFilePath.string(), ' ');
            if (dataOpt && !dataOpt->empty() && !dataOpt->front().empty()) {
                schedule.reserve(dataOpt->front().size());
                for (const auto& val : dataOpt->front()) {
                    try {
                        schedule.push_back(std::stoi(val));
                    } catch (...) {
                        std::cerr << "Error parsing schedule value: " << val << std::endl;
                        break;
                    }
                }
                return schedule;
            }
        }

        if (isDeviceSize) {
            schedule = utils::generatePoissonSchedule(1, targetOrSize, lambda);
        } else{
            schedule = utils::generatePoissonSchedule(1, (size_t) targetOrSize, lambda);
        }
        
        std::vector<std::vector<std::string>> strData(1);
        strData.front().reserve(schedule.size());
        for (int val : schedule) {
            strData.front().push_back(utils::toString(val));
        }
        
        if (!FileManager::write(scheduleFilePath.string(), strData, ' ')) {
            std::cerr << "Error writing to " << scheduleFilePath.string() << std::endl;
        }
        
        return schedule;
    }
}